
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dinh
 */
public class DisplayQuery extends javax.swing.JFrame {

    /**
     * Creates new form DisplayQuery
     */
    public DisplayQuery() {
        initComponents();
        showChiTiet();
    }
    
    final String url = "jdbc:mysql://localhost:3306/homework_db";
    final String user = "root";
    final String password = "";
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        TheoSuKien = new javax.swing.JButton();
        TheoGiaDinh = new javax.swing.JButton();
        ChiTiet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Quay lại ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        TheoSuKien.setText("Theo sự kiện");
        TheoSuKien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TheoSuKienActionPerformed(evt);
            }
        });

        TheoGiaDinh.setText("Theo gia đình");
        TheoGiaDinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TheoGiaDinhActionPerformed(evt);
            }
        });

        ChiTiet.setText("Chi tiết");
        ChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChiTietActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(TheoSuKien, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(TheoGiaDinh, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(ChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TheoGiaDinh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TheoSuKien, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Main m = new Main();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TheoSuKienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TheoSuKienActionPerformed
        // TODO add your handling code here:
        showTheoSuKien();
    }//GEN-LAST:event_TheoSuKienActionPerformed

    private void TheoGiaDinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TheoGiaDinhActionPerformed
        // TODO add your handling code here:
        showTheoGiaDinh();
    }//GEN-LAST:event_TheoGiaDinhActionPerformed

    private void ChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChiTietActionPerformed
        // TODO add your handling code here:
        showChiTiet();
    }//GEN-LAST:event_ChiTietActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void showChiTiet(){
        try{
            Connection con = DriverManager.getConnection(url, user, password);
            String sql = "SELECT Event.Name AS 'Tên sự kiện', Event.Year AS 'Năm', Recipient.Name AS 'Người nhận', Gift.Gift_Name AS Quà, Receive_Gift.Quantity AS 'Số lượng', Achievement.Achievement_Name AS 'Thành tích' "
                    + "FROM Event, Receive_Gift, Recipient, Gift, Achievement "
                    + "WHERE Event.ID = Receive_Gift.ID_Event "
                    + "AND Recipient.ID = Receive_Gift.ID_Recipient "
                    + "AND Gift.ID = Receive_Gift.ID_Gift "
                    + "AND Achievement.ID = Receive_Gift.ID_Achievement";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    public void showTheoGiaDinh(){
        try{
            Connection con = DriverManager.getConnection(url, user, password);
            String sql = "SELECT Family.Father AS 'Họ tên Bố', Family.Mother AS 'Họ tên Mẹ', Gift.Gift_Name AS 'Quà', Gift.Cost AS 'Giá', SUM(Receive_Gift.Quantity) AS 'Số lượng' "
                    + "FROM Family, Recipient, Receive_Gift, Gift "
                    + "WHERE Family.ID = Recipient.ID_Family "
                    + "AND Receive_Gift.ID_Recipient = Recipient.ID "
                    + "AND Receive_Gift.ID_Gift = Gift.ID "
                    + "GROUP BY Gift.ID";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    public void showTheoSuKien(){
        try{
            Connection con = DriverManager.getConnection(url, user, password);
            String sql = "SELECT Event.Name AS 'Tên sự kiện', Event.Year AS Năm, Gift.Gift_Name AS Quà, Gift.Cost AS Giá, Receive_Gift.Quantity AS 'Số lượng'"
                    + "FROM Event, Receive_Gift, Gift "
                    + "WHERE Event.ID = Receive_Gift.ID_Event "
                    + "AND Gift.ID = Receive_Gift.ID_Gift "
                    + "GROUP BY Event.ID, Gift.ID";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayQuery().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChiTiet;
    private javax.swing.JButton TheoGiaDinh;
    private javax.swing.JButton TheoSuKien;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
